### ISSUE TITLE
the bot stops to pull

### ISSUE THREAD

**Issue by zfradash** [Siterizer/new-world-fishing-bot#10]
The bot finds the fish, pulls it a little and then stops, until it completely loses the fish ...
Once lost, it starts again and then does the same thing.
Otherwise, the auto repair works well.

**Comment by Siterizer** [comment]
I may know why, can you pls change your visual settings to match this?
![image](https://user-images.githubusercontent.com/48980752/135419604-81cd3a71-a220-472f-a6ab-a4b41e86a5e7.png)

**Comment by DaGuT** [comment]
welp, at least it helped me a lot :)

thx

**Comment by Siterizer** [comment]
@DaGuT Okay, so if it's working, i am going to add this to a readme

**Comment by zfradash** [comment]
It worked for like 1 fish, now i have the same problem

**Comment by DaGuT** [comment]
> It worked for like 1 fish, now i have the same problem

does your "green overlay" cover the whole area after the first fish?

Cuz I found it changes position after the first catch sometimes and made my area bigger, now with new brightness, contrast and FoV, it's soooooooooooooooo great at fishing

**Comment by Siterizer** [comment]
@zfradash try to set positions like here:
https://youtu.be/fxEKNIxCn38

**Comment by spot88** [comment]
Have the same problems. Just stays at "pause" 
![image](https://user-images.githubusercontent.com/10884072/135512236-4439d19a-850e-48b8-8cf8-736bb14c03ba.png)

**Comment by moviedatascience** [comment]
I'm running into a very similar issue, but for me I don't enter finding fish

I have adjusted the settings per the video/instructions 
![image](https://user-images.githubusercontent.com/7471385/135545735-0b354084-2fc5-4ffd-95ce-d0c82829486a.png)

**Comment by moviedatascience** [comment]
It seems as though for me the global variable of continue_fishing stays false and I can't find what section is suppose to change that.

**Comment by Siterizer** [comment]
@spot88 @moviedatascience 
it's not fault of 'continue_fishing'. Bcs there are all the time cose fishing actions. What fails is the image recognition. Make sure that:
1. You have correct resolution
2. You have correct Graphics settings
3. You have corret brightness
4. Your green rectangle **completly** covers the fishing icons
5. **There are no green/brown/red things in green rectangle** (armor, sun, hands, hairs, factions tags etc)

**Comment by Logoniuss** [comment]
It works poorly, and I set the settings and whatever I do, it still works poorly, more or less at night, and when dawn, everything stops.

Thank you for the free bot and your work, but the quality of the bot is very poor, you need to constantly monitor the process, you need to come up with something to make the bot work universally.

**Comment by tkien212** [comment]
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Pause fishing
[INFO] Found a fish!
[INFO] Found a fish!
[INFO] Cast fishing rod
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing

Bot responded too slow to hook a fish and stuck at Pause fishing
My green box is smaller than the default settings also. So it should be faster - 301x450

**Comment by Logoniuss** [comment]
> I'm running into a very similar issue, but for me I don't enter finding fish
> 
> I have adjusted the settings per the video/instructions ![image](https://user-images.githubusercontent.com/7471385/135545735-0b354084-2fc5-4ffd-95ce-d0c82829486a.png)

Which file do you need to edit?

**Comment by Siterizer** [comment]
Add me on discord, and i will try to help you
Siterizer#8425

**Comment by Siterizer** [comment]
I think i am going to close the issue.
  Out of the ~ 22 people who contacted me today, there was no one that I wouldn't help.
  
  It's all about configuration your fishing position. In the future i will try to make the bot more 'immune; to such things or create yt video
