### ISSUE TITLE
Make `fishing_actions.reel_fish` cancellable.

### ISSUE THREAD

**Issue by liao-frank** [Siterizer/new-world-fishing-bot#103]
Suggestion: Make `fishing_actions.reel_fish` cancellable by other actions, such as [`3` (orange tension)](https://github.com/Siterizer/new-world-fishing-bot/blob/8ac8dfc586f81dfbd03e89880f6abc0947187683/functionality/image_recognition.py#L30-L31) and [`4` (red tension)](https://github.com/Siterizer/new-world-fishing-bot/blob/8ac8dfc586f81dfbd03e89880f6abc0947187683/functionality/image_recognition.py#L32-L33), to prevent fishing line from breaking. In other words, migrate away from synchronous `sleep` and allow `fishing_loop`/`image_recognition` to keep running while the bot is reeling.

e.g. change

https://github.com/Siterizer/new-world-fishing-bot/blob/8ac8dfc586f81dfbd03e89880f6abc0947187683/functionality/fishing_actions.py#L13-L18

to

```python
# Parameters:
#     state (dict): A dict of values representing the current state of the bot.
async def reel_fish(state):
    current_reel_start_ms = state['current_reel_start_ms']
    current_reel_timeout_ms = state['current_reel_timeout_ms']

    if (current_reel_start_ms is not None):
        time_since_reel_start_ms = (time.time() - current_reel_start_ms) / 1000
        if (time_since_reel_start_ms < current_reel_timeout_ms):
            debug("Continue reel from {} s ago".format(math.floor(time_since_reel_start_ms / 1000), 2))
            return

    reel_timeout = random_timeout(dict['fishing']['timeouts']['reeling'])

    debug("Start reel for {} s".format(reel_timeout))
    state['current_reel_start_ms'] = time.time()
    state['current_reel_timeout_ms'] = reel_timeout * 1000
    press_mouse_key()

    await asyncio.sleep(reel_timeout)
    if (state['current_reel_start_ms'] is not None):
        state['current_reel_start_ms'] = None
        state['current_reel_timeout_ms'] = None
        release_mouse_key()
```

and change

https://github.com/Siterizer/new-world-fishing-bot/blob/8ac8dfc586f81dfbd03e89880f6abc0947187683/functionality/fishing_loop.py#L44-L47

to

```python
state = {
    'current_reel_start_ms': None,
    'current_reel_timeout_ms': None,
}

    ...

    elif result_from_model == '2': #2 - model matched the green icon (reeling a fish in)
        info("Green color spotted, Reeling a fish")
        loop = asyncio.get_event_loop()
        loop.create_task(reel_fish(state))
        return '2'
```

`state` should be created and provided from `fishing_loop`. It can be provided to other fishing actions as well, who can check to see if there is a reel happening.

Most actions should early return if a reel is happening. But some actions, such as orange/red tension, can cancel the current reel by copying the last three lines of the async `reel_fish` example above.

I'm assuming Python's async library works like Javascript. Sorry if this example doesn't work out :(

**Comment by 53m1k0l0n** [comment]
Sorry but why so complicated?

is_reeling is simply used to avoid calling unnecessary methods that are not needed at the moment. 

fish_loop

`    elif result_from_model == '2' and not gv.is_reeling: #2 - model matched the green icon (reeling a fish in)
        info("Green color spotted, Reeling a fish")
        reel_fish()
        return '2'
    elif result_from_model == '3' and gv.is_reeling: #3 - model matched the orange icon (wait x sec)
        info("Orange color spotted, Pause fishing")
        pause()
        return '3'
    elif result_from_model == '4' and gv.is_reeling: #4 - model matched the red icon (wait x sec)
        info("Red color spotted, Pause fishing")
        pause()
        return '4'`

fish_action

`def reel_fish():
    debug("Reel fish")
    press_mouse_key()
    gv.is_reeling = True

def pause():
    gv.is_reeling = False
    release_mouse_key()
    pause_timeout = random_timeout_uniform(dict['fishing']['timeouts']['pause'])
    debug("Pause for: {} s".format(pause_timeout))
    sleep(pause_timeout)`

**Comment by liao-frank** [comment]
@53m1k0l0n 

That's a good option as well. It's just a problem of state management.

The image detection loop currently doesn't really care much about what the bot is doing when it issues a new action. It looks like there are a couple checks in place that validate past actions, but some refactoring could be good.

For example for me, `pause()` currently runs out-of-order frequently because of sunsets or people with red gear/company emblems running around. Adding code to `pause()` that deliberately makes assumptions about the previous action needs some careful consideration. What happens if the image detection thinks it's time to cast/repair/etc when the bot was just reeling? Will reeling ever be completed? What happens if it thinks it's time to pause when the bot wasn't just reeling? Will the bot accidentally cancel other actions and spiral out of control?

i.e. If Siterizer wants to make `reel_fish()` open-ended, meaning it doesn't both start and complete the action within the function, they would have to add carefully placed checks elsewhere in potentially many places to see if the bot is reeling. In the future, they might want to make other actions dependent on each other too. It might lead to a lot of spaghetti code and bugginess.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
