### ISSUE TITLE
Reeling fast 

### ISSUE THREAD

**Issue by HamzaAbdallah** [Siterizer/new-world-fishing-bot#105]
Hello, this is my first time using the bot! I have a problem that fishing is very fast when casting the bot don't wait to catch the fish it's  just reeling fast!
i know about this config
timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.7
      max: 1.7
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 0.5
      max: 1.0
      but i don't know what do you mean about 0.7 and 1.7!

**Comment by Siterizer** [comment]
@HamzaAbdallah What do you mean? like the bot is casting a fishing rod, and don't wait for 'notice' and re-casting again?
