### ISSUE TITLE
what is red color

### ISSUE THREAD

**Issue by shangus1234** [Siterizer/new-world-fishing-bot#109]
it runs very well, but sometimes it stops with the message 'red color spotted'. i just afk kicked with this bug(this bug keep happened until i got kicked)
is there any solutions sir?

**Comment by 53m1k0l0n** [comment]
'red color spotted' means that your line is about to break and the bot makes a break. Almost everyone is kicked because of "AFK". Only when you move you are apparently not kicked.

**Comment by N2Pee** [comment]
Make sure the detection box (the green box you set up) doesn't pick up anything red on the screen. The only red it should ever see in that box is the line tensioning.
