### ISSUE TITLE
pvp mode

### ISSUE THREAD

**Issue by Mo7ammadQ8** [Siterizer/new-world-fishing-bot#111]
I appreciate your work..

the bot is detecting pvp mode as red color of reeling

plus, it will be amazing if u could add a function that we can control the power of the cast .. because in some hotspot fishing spots .. we cant reach the fish

**Comment by dlucksinger** [comment]
You can control the power of the cast, read the document.

Don't flag pvp while using, problem solved.

**Comment by 53m1k0l0n** [comment]
> Don't flag pvp while using, problem solved.

This could well be a problem. I think I have seen that even if you are running around without Pvp, players from other factions who have Pvp on have red names.
