### ISSUE TITLE
Fish obtaining animation skip

### ISSUE THREAD

**Issue by ErovNest** [Siterizer/new-world-fishing-bot#116]
When obtaining fish, animation is being played, but it can be skipped with left click almost immediately. Adding such a feature will lead to significant increase of efficiency (each animation takes about 6 seconds to end).
Is it possible to upgrade the bot this way?

**Comment by jordan351** [comment]
very interesting

**Comment by 53m1k0l0n** [comment]
> When obtaining fish, animation is being played, but it can be skipped with left click almost immediately. Adding such a feature will lead to significant increase of efficiency (each animation takes about 6 seconds to end). Is it possible to upgrade the bot this way?

Yes it is possible. My version of the bot can do that (but was not easy to get there, stupid timing xD). The problem is the catching, sometimes the catch animation is canceled by another reel.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
