### ISSUE TITLE
Add field for brightness and contrast

### ISSUE THREAD

**Issue by CatsMeow492** [Siterizer/new-world-fishing-bot#12]
But has issues with detection with different brightness and contrast setting. Need to add more images to resources accounting for different setting and a place to prompt users for current settings

**Comment by CatsMeow492** [comment]
Self-assign

**Comment by Siterizer** [comment]
Sure, can do, but in the next week, would like to have some fun from game itself :D

**Comment by nezam7** [comment]
I agree, bot pauses way too much even when my eyes didnt see any red pixel on rectangle. fish went away and it keeps on repeating

**Comment by Siterizer** [comment]
Sorry, but i think too much work. But changed the color setings to default :) https://github.com/Siterizer/new-world-fishing-bot/pull/79
