### ISSUE TITLE
Little bug "found a fish and pull"

### ISSUE THREAD

**Issue by Mpaulo** [Siterizer/new-world-fishing-bot#120]
there's been a bug with me, I don't know if it's just me, but sometimes the bot fails in the "found a fish" part where it pulls the hook too late, after that in the next cast it pretty much puts all the time, totally throwing it away of the time determined in the bot, after this attempt it goes back to playing normally until it happens again.

**Comment by N2Pee** [comment]
Here's how I set my detection box up, hope it helps.

![fishingbox](https://user-images.githubusercontent.com/92459460/137456084-73881915-1ec8-4cd7-be66-02c2b22419da.png)

**Comment by Siterizer** [comment]
@N2Pee I don't know why, but your game looks kinda bright. Check Brightness/Contrast and siable any color-blind mode

**Comment by Mpaulo** [comment]
> confirming the same bug, i've noticed in the log that after "found a fish", it'll restart the loop from the beginning and cast when really it should be reeling. since there's a few second gap between the next cast loop, the fish breaks out of the line, as OP stated. my box is pretty small so I doubt it's a detection issue

yes, i set my box realy small and still got the bug

**Comment by GladstoneOG** [comment]
> confirming the same bug, i've noticed in the log that after "found a fish", it'll restart the loop from the beginning and cast when really it should be reeling. since there's a few second gap between the next cast loop, the fish breaks out of the line, as OP stated. my box is pretty small so I doubt it's a detection issue

I managed to solve this issue by changing the brightness and contrast to 50 50, hopefully this is helpful
