### ISSUE TITLE
Constanly crashing 

### ISSUE THREAD

**Issue by Azberk** [Siterizer/new-world-fishing-bot#126]
The last version u added with anti afk is crahsing after pushing start fishing button .

**Comment by CurlyLegend** [comment]
Im just getting AFK kicked even though it has Anti-AFK

**Comment by 53m1k0l0n** [comment]
> The last version u added with anti afk is crahsing after pushing start fishing button .

An error message would be helpful.

**Comment by Siterizer** [comment]
@Azberk Try to run .exe with cmd and copy error message

**Comment by CurlyLegend** [comment]
![image](https://user-images.githubusercontent.com/92329556/137568871-b87f5f2a-bde2-4851-a278-870fcc328baf.png)

**Comment by CurlyLegend** [comment]
Ill see if i can run with cmd and grab an error message next time

**Comment by AleKrizanek** [comment]
Mine also crashes around the 3 hour mark

**Comment by Siterizer** [comment]
The problem is i can't reproduce the bug myself on my pc/laptop so i don't know how to fix that :(((

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
