### ISSUE TITLE
Doesn't work properly when it's day time

### ISSUE THREAD

**Issue by tkien212** [Siterizer/new-world-fishing-bot#13]
The bot works perfectly fine when it's night-time in game. But when it changed to day time, it's unable to detect images properly.\

- Doesn't detect nothing? properly (doesn't cast hook)
- Doesn't detect caught fish fast enough
- Doesn't detect fish is hooked and start reeling, just sit there and wait for fish to run away

Graphic Settings:
https://i.imgur.com/vLlUsvW.jpeg

**Comment by Siterizer** [comment]
@tkien212 You know to be honest with you, a lot of people using the bot right now and everything is working. My teory is that your character is looking at something other than water (leaves, grass etc) and in the night-time the colors changes and are 'killing' the bot. Try to set the position like that:
https://i.imgur.com/usQXgFh.png
You see? mostly water

**Comment by Siterizer** [comment]
if it's still not working contact me on discord Siterizer#8425

**Comment by tkien212** [comment]
thanks for the info. I was referencing to the picture under 'Usage Guide' where you looking at tree/grass also (with green box)
I didn't know i should look at water

**Comment by Siterizer** [comment]
@tkien212 You don't have to in most cases. In my opinion the best way to use te bot is to find a river, with rock/mountain background. Do a few tries with position and you should be gucci (it may seem suspicious as you keep staring at the water)
