### ISSUE TITLE
Add keybindings option in config

### ISSUE THREAD

**Issue by So1m** [Siterizer/new-world-fishing-bot#131]
So we can change it ;)

key_bindings:
  repair: r
  confirm_repair: f
  equip_bait: r
  camera_free_look: n
  inventory: b
  fishing_view: F3

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
