### ISSUE TITLE
Trojan:Win32/Sabsik.FT.A!ml

### ISSUE THREAD

**Issue by Leebo-missile** [Siterizer/new-world-fishing-bot#137]
Windows detects latest update as a virus and deletes files, stating 
Trojan:Win32/Sabsik.FT.A!ml

**Comment by Siterizer** [comment]
@Leebo-missile You mean the .exe file?

**Comment by Leebo-missile** [comment]
![trojan](https://user-images.githubusercontent.com/54485295/137534400-4b65627c-8fcf-42ba-8767-d1c9b0b95781.png)
Yes the exe is being detected and quarantined by windows defender, as soon as unzipped or launched.  Past versions of the zip did not cause this to happen.
Can manually allow file to bypass, but prior versions seem to work fine, now that afk patch was reversed by devs

**Comment by Siterizer** [comment]
idk what to say, i think gonna close the issue
