### ISSUE TITLE
AFK Changes Reversed

### ISSUE THREAD

**Issue by Leebo-missile** [Siterizer/new-world-fishing-bot#138]
Seems the AFK changes were reversed by the Devs, the old versions without auto movement appear to be working as intended once again.
No longer getting kicked for AFK while fishing on version without auto walk

**Comment by 4LAU** [comment]
official statement here:

https://forums.newworld.com/t/notice-afk-system-changes/404631

**Comment by Siterizer** [comment]
I think they re-reversed it again XDD
