### ISSUE TITLE
Multi-threading to have a better reel-in

### ISSUE THREAD

**Issue by Hexalyse** [Siterizer/new-world-fishing-bot#14]
I took a look at your bot (since I was hesitating to make one myself, and good job on doing this, it's clean - I just added some more "organic" pauses where there were some sleep with fixed timings that could be seen as a bot) and noticed that for the reel in phase, you just reel in for a certain time, then check if it's green/orange/red. Which forces the bot to stop reeling in, even when it's still green, which might make it easily detectable if it does it too much. Humans don't really reel in by little bursts like this, when it's still obviously "very green" and won't turn orange soon.

A possible improvement (I might implement it if I find the motivation and time) would be to either:
- multi thread the bot to have the detection run as the mouse left button is pressed
- or even simpler and without needing threads : just press the left button, then run the detection function in a loop until the color goes to orange (you don't need to click for a certain time then stop clicking to check, just click and run the check continuously until orange is detected), when it does, stop clicking, and wait for some time, check if it indeed went green (if not wait more but shouldn't happen), then left flick and run the detection in a loop. This would look a bit more "human".

**Comment by Siterizer** [comment]
@Hexalyse Yes! it's excelent idea. It should be noted, however, that for people with weaker computers such 'reeling' may last long enough that the rope will be broken before the next action is detected (some fishes are hard to catch when using basic fishing rod). Therefore I decided that 'reeling' the fish should work for a certain number of seconds.

Thank you for the proposal to expand the app, I will definitely use it, but rather next week (currently I have a lot of fun with leveling and pvp)

**Comment by Hexalyse** [comment]
Ah yes indeed... I didn't think about the fact that on lower end CPUs (especially with the game running), detection with opencv might take a noticeably long time.

It would be good then, to allow the user to choose between the two modes of reeling. It would complicate the code somehow, but it's the most flexible option.

I still didn't try PvP despite being lvl 20+. I need to start looking how it works in this game and join in this week end, since PvP is almost the only thing that interest me in MMOs.

**Comment by Siterizer** [comment]
@Hexalyse You should definitely try teritory claims, fun as hell XD

But about the configuration yes, it would be a perfect solution. In the future i even wated to move all of the variables in the config.xml to the user interface
