### ISSUE TITLE
cast range is ignored

### ISSUE THREAD

**Issue by frakc** [Siterizer/new-world-fishing-bot#145]
Hello, thanks for grate bot:) issue with casting distance

i modified config.yaml to
    cast:
      min: 0.9
      max: 1.0
      
but the road is still cast to 0.5

**Comment by 4LAU** [comment]
those are seconds, not percentage points

**Comment by frakc** [comment]
Oh. And can we controll distance?  maximum cast make minigame easier

**Comment by Siterizer** [comment]
@frakc Yes, if you want 'max' distance change 'cast' to 2.5-3.0. This should work
