### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by Trigun87** [Siterizer/new-world-fishing-bot#146]
u should add the same function that create the box for the areas (fishing/repair/bait) for when it detect the red/orange, since sometimes u find the bot blocked and u can easy know what was the problem if u see the box

and u need to doublecheck if u have the fishroad in the hand since sometimes it get the weapon and start attack (the color on the R for equip a bait?)

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
