### ISSUE TITLE
Does not cast the fishing rod 

### ISSUE THREAD

**Issue by Derisska** [Siterizer/new-world-fishing-bot#149]
ValueError: scale < 0 
what am I doing wrong?
Help me please :)

**Comment by Siterizer** [comment]
@Derisska Do you have dual monitor setup? It looks like the bot is not able to calculate negative pixels

**Comment by SynaX1** [comment]
Laptop 1080p?

**Comment by Derisska** [comment]
> Ноутбук 1080p?

Yes

**Comment by Siterizer** [comment]
You can try to add me on Discord, and sheare me your screen Siterizer#8425
