### ISSUE TITLE
Straight up not working.

### ISSUE THREAD

**Issue by blitzy13** [Siterizer/new-world-fishing-bot#15]
The program log shows it is detecting the actions in the gamewhen i fish manually, but it does not seem capable of doing the fishing itself.

**Comment by blitzy13** [comment]
Ope my bad, i sort of got it working. although abobut half the time a fish is on the line, the log says Pause Fishing and stops reeling in

**Comment by tkien212** [comment]
you probably have the same problem as mine
your whole screen needs to be water (look straight down)

**Comment by Siterizer** [comment]
one guy had issue with the red color of their character hairs xd. It's hard in some cases to get the bot running. But when it's done bot can fish 24/7. But remember to not leaving him alone in case of the administrator would like to visit you

**Comment by blitzy13** [comment]
My bad seems like i just needed to finagle it for a while, although i watched it for about 3 hours it worked great, I left the house for a bit and got kicked, not sure if it was afk or what it was.
