### ISSUE TITLE
Can't Reel

### ISSUE THREAD

**Issue by Xalxal** [Siterizer/new-world-fishing-bot#152]
Hey there, great bot thanks for making it. But i've a question, on the defaault setting with ironwood fishing pole, it can't reel the fish. I mean i tweak the reeling values and pause values but can't make it work. Any suggestions to that?

**Comment by bengiosis** [comment]
What are your visual settings?

**Comment by Xalxal** [comment]
my brightness was 51 that fixed the issue but it sometimes can't catch the fish now.  I tweaked some numbers again but it didnt solve it :/

**Comment by Xalxal** [comment]
it's unstable, works for a 3-4 times and  misses after fishes after that. My setting are like yours exactly, i dont know what's wrong

**Comment by Siterizer** [comment]
Add me on Discord, it's hard to tell you what is the cause without seeing the game and bot on your pc Siterizer#8425
