### ISSUE TITLE
Pause 6s after almost every command

### ISSUE THREAD

**Issue by Pauliusj92** [Siterizer/new-world-fishing-bot#155]
Maybe anyone has any ideas?
I do not get it where it comes from, but after almost every command i get pause 6s. Therefore it misses the catch, the reel, everything.  Any ideas?

P.S i even minimized every command intervals, and this seems not affected by the config.

**Comment by Marttern** [comment]
I have the same issue, even with the slowest config settings and small scan windows, I miss reels, it doesn't equip bait, it is slow to re-cast after catching fish (if it manages to spot it when it's caught), is there any way I can give more information about the problem I'm encountering? I'd be happy to pay for the bot if it worked effectively without babysitting

**Comment by Siterizer** [comment]
I know about all of those issues, i will mark this one duplicate, and copy-paste mys tatement here:

The bot I created in free time while changing job. I' got plenty of free time for doing that. But right now 3 weeks after the 1st bot release it's hard for me. Like
1. Family
2. New Job :DD 
3. Playing the game (PvP, etc)
4. Like 40 private messages on Discord with help in configuration/download etc. 
  I am so sorry for that, but well points 1-3 are more important for me then updating the bot. I guess that's the con of "free bot". In paid solutions I am sure developers have more time to keep their bots up to date. Again so sorry for that didn't think that this thing would become so popular with such great community 
  like none on my friends or friends of friends have a project like that (community/amount of issues/stars :DD) And I am very grateful for that. Love you ❤️ 
And about PayPal, sorry don't have one. Only BTC/ETH wallets. If you can't donate with that that's ok. What you can do for me is take that money and buy some food/donate nearest animal shelter 😉
