### ISSUE TITLE
BLACK SCREEN AND BOT STOP.

### ISSUE THREAD

**Issue by volk4nn123** [Siterizer/new-world-fishing-bot#156]
Bot is working well.. but 2 3 hours later, the black screen comes and the bot stops, I have to close the game and open it.
Thanx all

**Comment by JANIS1289** [comment]
same, cant even get to work it, black screen at the start

**Comment by Siterizer** [comment]
Where the black screen appears? And what is your PC specs? Maybe it's because of high PC usage

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
