### ISSUE TITLE
Feature requests.

### ISSUE THREAD

**Issue by eXqusic** [Siterizer/new-world-fishing-bot#16]
Can we get the following please? :)
- Use bait
- Customizable keybind to toggle the start fishing button.
- Randomized delay
- Obfuscation

**Comment by Siterizer** [comment]
Sure, they look like very good ideas, btw what do you mean by 'Obfuscation'?

**Comment by eXqusic** [comment]
Obfuscation when compiling it to an exe to prevent new world anticheat seeing it as the same program on a lot of computers.

**Comment by DaGuT** [comment]
https://github.com/Siterizer/new-world-fishing-bot/pull/21

if you use python version, you can try that PR with bait usage :)

**Comment by Hexalyse** [comment]
> 
> 
> Obfuscation when compiling it to an exe to prevent new world anticheat seeing it as the same program on a lot of computers.

Don't use a .exe then. Just run the code via Python, it does the same and you don't get a .exe that can be checked against a list of filehashes. Also, it's more secure since it removes the need to trust the .exe you're downloading.

**Comment by Siterizer** [comment]
it's all done by now (will think about Obfuscation later), will close the issue
