### ISSUE TITLE
does not work for me 

### ISSUE THREAD

**Issue by Mishixp** [Siterizer/new-world-fishing-bot#17]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "gui\gui_functions.py", line 47, in start_fishing
  File "functionality\fishing_loop.py", line 13, in fishing_loop
  File "functionality\fishing_loop.py", line 28, in call_appropriate_fishing_action
  File "functionality\image_recognition.py", line 17, in image_recognition_result
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

I am getting this error in log. Can you help me?

**Comment by Siterizer** [comment]
What is you windows version. Is it 10? It looks like some of the windows build in files are not working. If i were you i would reinstall the system.
  One guy had the same issue, so he download python, libraries and ran the code directly from python

**Comment by oytuns** [comment]
same error how to fix

**Comment by Siterizer** [comment]
@oytuns I don't know 😞 The problem is it's about your windows and no The bot code itself. So i can't reproduce it on my pc. Instead of running .exe file You should download install and run python version

**Comment by Kerozen07** [comment]
Ohhh no, same for me 😞

**Comment by Siterizer** [comment]
@Kerozen07 sorry, i don't know how to help with that. That is beyond my knowledge

**Comment by Mishixp** [comment]
> What is you windows version. Is it 10? It looks like some of the windows build in files are not working. If i were you i would reinstall the system. One guy had the same issue, so he download python, libraries and ran the code directly from python

I ll try that, thanks for answering.

**Comment by vpechenik** [comment]
> What is you windows version. Is it 10? It looks like some of the windows build in files are not working. If i were you i would reinstall the system. One guy had the same issue, so he download python, libraries and ran the code directly from python

Can you write how to do it? Never used python

**Comment by Acanis87** [comment]
It didnt fix it for me. I had it C:/new-world-fishing-bot with the same error.

Downgrading the Python version finally did help me.
