### ISSUE TITLE
Possible detection?

### ISSUE THREAD

**Issue by F1Howard** [Siterizer/new-world-fishing-bot#176]
I ran the bot for ~6hour today. every one to two hours i would run and gather more bait and nearby resources. after one such run, i had been fishing for ~1hour when the client began to hang when a fish was caught. almost like the clinet was crashing. this happened 3 times, not in a row, but within 5minutes of each other. on the third, I was disconnected from the game and received a message stating "Suspicious Software or Corrupted Install Detected"

any ideas? Has ags detected the script?  

For reference i did not have auto repairs or auto bait active.

**Comment by DaGuT** [comment]
Nah, the game just sucks.

That happens from time to time even with normal fishing. It stucks, you release LMB, but it still reels the fish. It can show red waves even when everything is green. It can stuck anytime etc :)

It happened to me yesterday like every 5-10 mins during normal fishing.
