### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by caseyjames95** [Siterizer/new-world-fishing-bot#18]
Good afternoon! Everything is solid but I run into one small problem. Once gosh is hooked it’ll start to reel the pauses for too long and fish gets away. I tried playing with pause times and couldn’t come up with any results.

 If help it get passed the initial reel in, I’ll finish everything off just fine. Maybe it’s user error? Everything looks great though thanks for the awesome crispy.

**Comment by Siterizer** [comment]
Do after starting The 'minigame' The output od only like
Pause
Pause
Pause
Pause right?
If so you should check if on the area of green rectangle are any red colors (hair, armor weapon, sun etc)

**Comment by caseyjames95** [comment]
I’ll try that out and make the area smaller. But yes right after I hooks it’s does

Pause
Pause 

then the fish unhooks

**Comment by caseyjames95** [comment]
This is all good I realized I misread he contrast #
