### ISSUE TITLE
Bannable?

### ISSUE THREAD

**Issue by bonxz** [Siterizer/new-world-fishing-bot#19]
I this thing here bannable or even detectable?

**Comment by bonxz** [comment]
I this thing here bannable or even detectable?

**Comment by nezam7** [comment]
Don't think so.. Unless you use it extremely heavy and reported by someone else.

**Comment by Siterizer** [comment]
it depends, if you plan to leave the bot for 24 hours unattended and the admin will pay you a visit, it may not be too interesting. But from the purely 'hardware' level, to my knowledge, its hard to detect it (if they could, it would be a lot of bans by now)
