### ISSUE TITLE
Problems with breaks interval?

### ISSUE THREAD

**Issue by xXjojojXx** [Siterizer/new-world-fishing-bot#191]
settings

1920x1080
Low graphics
50 brightness
50 contrast

[DEBUG] starting new loop
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 2.25 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.86 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 1.13 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 1.63 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 1.96 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.69 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 1.29 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[DEBUG] starting new loop
[INFO] Red color spotted, Pause fishing
[DEBUG] Pause for: 17.66 s
[DEBUG] starting new loop
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.91 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.94 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.5 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 1.53 s
[DEBUG] Pause for: 5 s
[DEBUG] press b
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 6 s
[DEBUG] release b
[DEBUG] Pause for: 1 s
[DEBUG] Pause for: 0.8 s

**Comment by Tubben** [comment]
> settings
> 
> 1920x1080 Low graphics 50 brightness 50 contrast
> 
> [DEBUG] starting new loop [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 2.25 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.86 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 1.13 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 1.63 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 1.96 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.69 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 1.29 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [DEBUG] starting new loop [INFO] Red color spotted, Pause fishing [DEBUG] Pause for: 17.66 s [DEBUG] starting new loop [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.91 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.94 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.5 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 1.53 s [DEBUG] Pause for: 5 s [DEBUG] press b [DEBUG] starting new loop [INFO] Cast fishing rod [DEBUG] Pause for: 6 s [DEBUG] release b [DEBUG] Pause for: 1 s [DEBUG] Pause for: 0.8 s

Exact the same happens for me also. Just one time a fish did bite before he canceled the cast and he started to reel.
