### ISSUE TITLE
Detected ( "Banned :(" )

### ISSUE THREAD

**Issue by NightWishKsK** [Siterizer/new-world-fishing-bot#194]
Hello, as of today, when I entered the game, I encountered this, I was not in the game when I was banned, I guess my game ends here, I will never use it again after the ban is lifted. I'm sorry I'm using translation

![Adsız](https://user-images.githubusercontent.com/93011931/138520183-28185cb5-e598-462e-86f6-90d349ea3bc6.jpg)

**Comment by tallglen** [comment]
This ban feels like you were manually reported by a bunch of people.
