### ISSUE TITLE
Can not press on "Stop Fishing"

### ISSUE THREAD

**Issue by gumbassus** [Siterizer/new-world-fishing-bot#195]
Hey, so far everything works fine with some custom settings but i just cant press on "stop fishing" because the bot window itself always freezes and i have to force close it. Is there a way or a button to stop fishing? its really annoying sometimes since my mouse goes all over the place

**Comment by 4rak007** [comment]
there is solution when it start fish before it catch the fish u can stop it without freezing the bot

**Comment by innellea** [comment]
Ctrl+C on the terminal to stop it.
