### ISSUE TITLE
Some good spot? 

### ISSUE THREAD

**Issue by nezam7** [Siterizer/new-world-fishing-bot#20]
Can someone share their spot which has better 'non pause' detection? Even when dawn

Kindly share your brightness setting as well.

**Comment by raphalimam** [comment]
Dont know any good spot to fish, you can search in the internet, but if it's just tu avoid the the pause because of the colors, you can just aim totally at the water, so only it appears on the screen, so far that worked for me.

**Comment by nezam7** [comment]
> Dont know any good spot to fish, you can search in the internet, but if it's just tu avoid the the pause because of the colors, you can just aim totally at the water, so only it appears on the screen, so far that worked for me.

Sometimes the dawn light still affecting me. But thanks for the idea
