### ISSUE TITLE
Kicked for bot detection

### ISSUE THREAD

**Issue by Sevenn56** [Siterizer/new-world-fishing-bot#201]
![IMG-20211024-WA0009](https://user-images.githubusercontent.com/93104281/138619114-07ee7387-0a3e-4629-8227-6cadbb26e95a.jpg)

Hey, i was kicked from thé game (not ban) with this message.
I was in à random area with no People.
I think boting is done !

**Comment by innellea** [comment]
Have you been able to log back in? No ban?
