### ISSUE TITLE
Repairing stuck after several hours of usage

### ISSUE THREAD

**Issue by DataSiens** [Siterizer/new-world-fishing-bot#203]
Repairing stops working after several hours of usage.
Seems like it doesn't click the button.

For a first few hours it works as intended, but then suddenly stops clicking the fishing rod button on the inventory, leaving the rod broken.

I have already tried changing the min and max wait time for repair in config, but still this keeps occurring.

Any idea on why and how to fix thisv

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
