### ISSUE TITLE
Seems like it has finally been detected

### ISSUE THREAD

**Issue by syntax001** [Siterizer/new-world-fishing-bot#204]
![2dd](https://user-images.githubusercontent.com/71074471/138679908-685dd57b-87de-4cb7-9ae5-9d05bf9e4892.png)
Ran the bot anywhere from 5 minutes to 5 hours. I have no way of knowing, i was away from PC for 5 hours, and when i came back this was on screen. I have no other software running that would be detected as malicious. 

Edit: Its worth noting: i did not use the EXE, i cloned the code and ran it via CMD. I also made my own anti AFK module before it was released to this github.

Weirdly enough i am not banned, even though the kick states it found "Suspicious Software"...

I would say use it at own risk? But then again, they dont seem to be banning for it. Maybe you gotta get kicked a certain amount of times for this "offense" before they ban you.

Edit2: Just wanted to mention also: I find it very unlikely that i got reported by somebody. I was fishing at a very unpopulated spot, and it was from 7am to 12pm on a monday. My server barely has anybody playing at those times.

**Comment by 4LAU** [comment]
pretty sure you got reported. record your next afk session and play back the video
