### ISSUE TITLE
Pulling rod before fish hooked

### ISSUE THREAD

**Issue by sirR9** [Siterizer/new-world-fishing-bot#209]
Hey, I'm noticing that my cast times out and just pulls the rod after about 5 seconds.

I've tried different spots, different gear on, and attempted to mirror the setup image as close as possible.

I'm on a 1440p monitor, but downscaled my resolution to 1080p and have my graphics set to low.

Any advice?

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
