### ISSUE TITLE
Random 6 second pauses during reeling, fish gets away everytime

### ISSUE THREAD

**Issue by zune127** [Siterizer/new-world-fishing-bot#214]
1440p monitor with 1080p downscaled in windowed mode.

Doing everything as listed in setup low graphics, colorblind mode disabled.

Trying to fish in Weaver's fen

Bot does everything right then during reeling it will stop and pause for 6 seconds, reel a little bit, then pause for 6 seconds again, and the fish will get away.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
