### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by JohnboyHD** [Siterizer/new-world-fishing-bot#216]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\Graß\Desktop\new-world-fishing-bot-1.2.0\Scripts\python.exe -m pip install --upgrade pip' command. 

was muss ich machen ?

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
