### ISSUE TITLE
Bot issue: RESOLUTIONS

### ISSUE THREAD

**Issue by ITgamers** [Siterizer/new-world-fishing-bot#217]
Siterizer, you're a boss brother. 
Thank you.

Bot issues: Resolutions(Read if you are having issues). 

There are a-lot of smart people in this form taking advantage of this great program Siterizer created. That being said understand that Siterizer has created this and decided to share it with you all for FREE. That being said, I check this tread on a daily, several times a day and see a trend. I would like to make a master fix thread to not have duplicated posts. 

If you have discovered a bug and a resolution post it here. I'll add it to the post. 

Rule #1:  Read the directions in its entirety. They are well made and should resolve most people’s issues. 
Rule #2: You must have the correct resolution and settings (Read: Rule #1) 

Rule #3: If trouble shooting, reset settings to default for bot. 
Ruke #4: Make sure color blind mode is OFF in game settings.

Issues and resolutions:
Issue: My bot doesn’t reel in all the way and it hangs letting the fish escape. 
How it works: The bot reads onscreen icons and colors (red=stop).
Resolution: You must adjust your X and Y axis to include height and width. 
If you do not stretch the height of the bot range you will not be able to have a complete reel. Click the check button to see what the bot range is. If you are on an elevated platform you will need to have the range stretched to the bottom of the screen. 
This leads to your health bar. If you stretch the range to the bottom of your screen and the health bar is red it will no reel due to it reading the red health bar. 
RED- If there is a monolith in the back ground that is red, a pvp player that decides to stand right in front of you, or you have a legendary corrupted fishing pool that emits RED the bot will stop fishing/reeling in. Why? Read “How it works”. 

Issue: My bot doesn’t repair my fishing pool/ gets stuck in inventory
How it works: The bot will imitate the actions required to repair the fishing pool 
Resolution: First set the bot repair to 5 seconds. Second go into your bot folder and find folder/file Resources>config. Open this with an editor like notepad++ (what I use). 
Third find repair in the text and change its min to .02. Save and run the bot. Test if it still hangs if it does, stop the bot close it out change the min to .03 and test. If it still hangs repeat until it doesn’t hang. Min.04 min.05… You shouldn’t have to go anything past .05. (I keep mine at Min.03) the Max setting is default.
Once you have found your sweet spot go back to the bot and change your repair to something more reasonable. (I keep mine at 1000) 

Further instructions and setting descriptions are laid out in the Personalization guide in the (Rule #1)

Issue: My bot deos not reset back to position/ character stay looking at the floor.
How it works: The bot will imitate the actions required to center the camera with keyboard letter: B. 
Resolution:  Make sure free look in your in game settings is set to B. If it is B. Set your in game settings back to default and change the free look back to B. Make sure your windows scale is set to 100%. 

Example I run a 1440p panel ultra wide. I leave my windows scale at 100 and change the game to windowed 1920x1080 and adjust my settings for the bot that way.
Issue: Can’t run bot
How it works: Python. 
Resolution: Install python from python.org. Run bot.exe as admin. Right click bot, run as admin. You can also right click bot.exe, properties and set to run as admin every time.
Depending on your antivirus it could false flag the bot as a virus. Add bot.exe to your antivirus white list. As there is too many different variations of antiviruses I will not cover how to do that. You will have to google how to whitelist a program with your antivirus. It is very easy.

Issue: Anti-AFK – It’s too aggressive/walks to far/ Walks me off the dock
How it works: Anti AFK method/ Walking 6 paces left 6 paces right. 
Resolution: Go into resources > config open the config file in your text editor (I use notepad++).
Find the walking setting and. Change min and max to 0.0. This will cause you to do a slight shuffle and essentially keep you in place.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
