### ISSUE TITLE
[Improvement] show rectangles on top

### ISSUE THREAD

**Issue by Culain** [Siterizer/new-world-fishing-bot#218]
Hello, 

i would suggest to add the line `window.attributes('-topmost', True)` in the popup_rectangle_window function (right below the fullscreen atribute). This will allow the rectangle to stay on top of the game window and gives the chance to setup the correct viewing angle to be sure that the marker is in the expected area.

i would like to make this a pull request, but i'm too noob to set it up :S

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
