### ISSUE TITLE
[Improvement Idea] Set Rectangle and Buttons with Mouse

### ISSUE THREAD

**Issue by Culain** [Siterizer/new-world-fishing-bot#219]
Hello again,

it would be very convenient, if we could select the area where we want the rectangle to be with either two mouse clicks (top left and bottom right corner) or by draging a selection rectangle across the window. 
The buttons for repairing and bait selection could be set with a single mouse click.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
