### ISSUE TITLE
Delay in hooking

### ISSUE THREAD

**Issue by BenJ180** [Siterizer/new-world-fishing-bot#22]
Hey guys. For some reason the bot tries to hook just after the hook has been missed, like its a bit too slow. Any way to change this?

**Comment by Siterizer** [comment]
Try to make The rectangle smaller. The smaller The rectangle The fever pixeles The bot have to check. The faster the bot will work

**Comment by DaGuT** [comment]
there is a high chance your pc is now powerful enough to process zone you have set with a delay set in config.

Go to https://github.com/Siterizer/new-world-fishing-bot/blob/main/resources/config.yml

Find 
```    notice:
      min: 1.5
      max: 2.0```

and set them to lower numbers. That'll do fine

**Comment by Siterizer** [comment]
@DaGuT don't think that change timeout will help. Notice timeout is The time bot holds mouse after noticing the fish. Do It wont help with too slow processing

**Comment by BenJ180** [comment]
Hey guys, confirmed that a smaller search box fixed the issues :)
