### ISSUE TITLE
After patch today 10/27 bot seems flaky

### ISSUE THREAD

**Issue by menguepatel** [Siterizer/new-world-fishing-bot#220]
been running it without problem for past several weeks, on latest version (13 days ago it seems?) and now today occasionally it just won't click to reel in.  Watching the debug window/log it shows that it sees the green, but just lets the counter dwindle.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
