### ISSUE TITLE
Worked before, stopped working 2 nights ago

### ISSUE THREAD

**Issue by Random-txt** [Siterizer/new-world-fishing-bot#224]
I was using your bot for a while without issues. But since 2 nights, the bot doesn't notice a fish catching the bait. I set the config back to vanilla and still not being detected. In the console all it says is casting rod? I don't know what caused this issue because it was working with the same settings before.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
