### ISSUE TITLE
Death while fishing

### ISSUE THREAD

**Issue by joravernigusya** [Siterizer/new-world-fishing-bot#225]
The question is not really on the topic, but maybe it happened to someone. The bot was standing on a fishing spot far from civilization at a waterfall where there are no animals. PVP mode was turned off. And after a while I'm dead. I didn't even notice how it happened, I was reborn already in the city. Maybe the GM is running around and killing bots? :D

**Comment by frankfuu** [comment]
Hi @joravernigusya , i'm interested in knowing the location of this said place as i've been trying to look for hours and haven't been able to find a "safe" fishing spot away from mobs of non retreatable distance. Care to share?
