### ISSUE TITLE
is it safe ? 

### ISSUE THREAD

**Issue by jindoggo96** [Siterizer/new-world-fishing-bot#23]
https://www.virustotal.com/gui/file/8d0e3be5c06e4de00a50053f579caeca94d313630a83be387ff8c31b3fedfa3f

**Comment by Hexalyse** [comment]
You could just download the code and run it with Python. Then you don't have to trust the maintainer of the repo uploading a .exe that is "safe".

It's not that hard : install python, execute the few `pip install` commands given in the readme, and run the bot.py file.

**Comment by rogeriocamorim** [comment]
Also, no "hack / bot" is 100% safe if you are left unattended. Do not run it 24/7. it is not humanly possible.

**Comment by Siterizer** [comment]
That's right. The python version is the best way to run the bot. What if (for example) someone will take over my github account and replace bot.zip with other zip file that is virus. You never know what is inside .exe file.
