### ISSUE TITLE
2.0 doesn’t return to correct fishing position 

### ISSUE THREAD

**Issue by Kirball** [Siterizer/new-world-fishing-bot#231]
The latest version doesn’t return back to facing the correct way after a random amount of casts. It seems to be random to me sometimes it runs for a while before it gets turned another direction (about 90 degrees to the left) and sometimes it gets turned after the first cast.

**Comment by Kirball** [comment]
I just tried again and it’s not returning after the first fish caught. I even ran 1.2 and it’s doing the same thing. B is still set as my free look button. Any ideas what’s causing this?

**Comment by kevinlotz** [comment]
I prsssed b once and it started working normally idk

**Comment by Kirball** [comment]
It appears free look quit working. Restarted the game, restarted the PC it randomly began working again after about 30 mins.

**Comment by kevinlotz** [comment]
I've had it stop workong randomly too. Ctrl v is closing instead of interripting me too. Worse is my green isn't always getting recognized causing loop to reset and recasting.

**Comment by Siterizer** [comment]
@kevinlotz @Kirball Can you try to click 'restore default' button in key binds and assign 'b' again? I think it's in-game bug

**Comment by Kirball** [comment]
It cleared up for me but someone told me they were able to fix it before by pressing tab 2x so that’s a possible fix if free look quits for me again in the future.
