### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Kirball** [Siterizer/new-world-fishing-bot#234]
So 2.0 contains a Trojan horse?  Not cool.  Windows says it’s a virus and a scan found that it’s installed a virus.

**Comment by syntax001** [comment]
You have access to the source code.... You can literally check exactly what the program does and decide whether or not its a "trojan". Im using a much more advanced anti-malware than Windows defender and it has no problem with 2.0.0.

**Comment by syntax001** [comment]
https://www.virustotal.com/gui/file/74fb1bab14d341586b43064a35074b51e977b8b51e0d839258cf5a257dcb2a61/detection


Looks like you're using McAfee. McAfee is a joke of an antimalware program. I'd sooner go without an antimalware program, than install McAfee on my system. As you can see, the 68 other (and vastly superior) antimalware programs found nothing wrong with the EXE.

**Comment by Kirball** [comment]
I don’t use the .exe as I have no need for it (that I’m aware of). I don’t use mcafee. Why are the older versions clean and this one isn’t?  I’ll just use 1.2 in the meantime. Having access to the source code does me no good as I don’t code so . . .

**Comment by syntax001** [comment]
Well how do you run the code? Im guessing in a python virtual environment then? If you know how to clone code and setup a python virtual environment it shouldnt be rocket science to figure out what the code does. Its fairly simple. I have absolutely no experience in Python either. 
Also, the EXE runs off the same code youre cloning, so i dont see the issue. If 67 out of 68 security programs are saying its clean, its clean. The funny thing is, windows defender also marked the EXE as clean on Virustotal, so im not sure whats up with your machine.

**Comment by Kirball** [comment]
Windows completely blocks me from running the script.

**Comment by syntax001** [comment]
Then you'll have to disable Windows Defender while you run it. There's not much else I can recommend you when you don't give the actual message Windows Defender gives you, or attach a screenshot. 
And if you trust Windows Defender more than the 68 other programs that scanned the file then I don't know what to tell you.

**Comment by Kirball** [comment]
I installed python on my box. I just download the .zip extract it change the config file to suit my needs and run the script. 2.0 worked fine last night. When I started my PC today iI was blocked from running the script. Defender found 2 viruses installed and removed them. The script was removed in the virus removal. Seems pretty sus.

**Comment by syntax001** [comment]
Its not sus really, its pretty simple. You either got a virus from somewhere else, or Windows Defender is just being Windows Defender. Again, if you hold Windows Defender to such high standards then i guess you'll have to go back to an earlier version. But the VirusTotal link i posted really should be the end of discussion. There's nothing malicious in the script. If there was, don't you think the 10+ other Python programmers who have forked this code and made improvement suggestions would've noticed?

**Comment by Kirball** [comment]
2.0 has already been forked?

**Comment by syntax001** [comment]
2.0 was inspired by the pull request from srhinos. so srhinos has worked a lot with the older version. tallglen from one of the other issues is working with 2.0 to find a solution to animation skipping. Im also testing 2.0 and customizing it a bit to my liking, (although as i said i have NO experience in python. I do understand majority of the code however)

**Comment by Kirball** [comment]
https://imgur.com/a/hqrhYwT

**Comment by MrGEnatgr** [comment]
no virus detection im also using windows defender nothing showed up for me

**Comment by syntax001** [comment]
> https://imgur.com/a/hqrhYwT

Use an earlier version if you're paranoid. However if Siterizers goal was to make malware, do you really think he would wait until 2.0 to implement it? 2.0 is even "hidden" on a different branch, so likely most of people are still using version 1. There are tons of fishing bots out there, you could also just pick a different one.

**Comment by Siterizer** [comment]
Well Remember that if a repository contains
1. Sexual content
2. Hidden crypto mining
3. Wiruses.
4. Etc
Then i can get perma banned on my github account.
  And github is my programming portfolio so a big part of my resume. Maybe that would convince You 😁

**Comment by ITgamers** [comment]
Read up on// False positives

**Comment by syntax001** [comment]
> Read up on// False positives

I mean false positive would technically imply the program shares some traits with virus behavior (but not actual virus behavior, thus 'false' positive), but thats not even the case here so i have no idea what Windows Defender is doing on that mans machine :D

**Comment by wade217** [comment]
OP is not the only person reporting this issue. I know two people that have also reported this as malicious.

**Comment by wade217** [comment]
Too many fingers in the pie at this point.

"Dev" claims he's working on a resume but I mean....  fishing bots and his profile would suggest otherwise. 

B E W A R E

**Comment by syntax001** [comment]
> Too many fingers in the pie at this point.
> 
> "Dev" claims he's working on a resume but I mean.... fishing bots and his profile would suggest otherwise.
> 
> B E W A R E

dude.. you have access to every single line of code that gets executed on your machine. its right here. read it, and decide for yourself, if 68 security vendors telling you its safe isnt enough.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
