### ISSUE TITLE
Has the anti AFK of 2.0 been cancelled

### ISSUE THREAD

**Issue by qq1748244285** [Siterizer/new-world-fishing-bot#235]
The efficiency and performance of 2.0 feel much better than 1.2, but it seems that the anti AFK is cancelled. Although I haven't dropped the line, maybe Amazon has turned off the AFK mechanism? I found an occasional problem in 2.0. After fishing, the angle of view will shift to the left and move 90 degrees. My friends and I have encountered such a problem

**Comment by Siterizer** [comment]
@qq1748244285 Yes, i removed code that forced character to move. The reason od that Amazon removed anti-afk for characters that fish. To prevent The rotation You can click 'reset to default' button then assign 'b' again. That should help

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
