### ISSUE TITLE
Errors with v.2.0.0

### ISSUE THREAD

**Issue by R3knqrp** [Siterizer/new-world-fishing-bot#236]
I've been encountering new problems with the new version. Even though the image detection is a lot better, and it has never missed reeling a fish, the bot occasionally cancels the reeling animation, meaning that while reeling the fish in, it stops reeling, and starts casting the rod (in the console) while the fish slowly runs away until the bot starts reeling again after a delay from the casting. Also, I've been encountering another problem with the camera, I think you should increase the time it waits until it releases the key "b" from 6 seconds to 7-8 seconds just to make sure that there wouldn't be an instance of an early release of the b key.

**Comment by R3knqrp** [comment]
https://user-images.githubusercontent.com/93481650/139591570-8bc1084f-e4e1-4984-a81d-56310985c803.mp4

**Comment by 4rak007** [comment]
Got same problem here

**Comment by R3knqrp** [comment]
Nvm problem is solved.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
