### ISSUE TITLE
v2.0.0 Problem with false positive fish detection.

### ISSUE THREAD

**Issue by phGH** [Siterizer/new-world-fishing-bot#237]
Botting on vmware, All was working fine with v1.2.1, but on v2.0.0 getting a lot of false positive fish detection.
Any ideas how it can be solved?

https://user-images.githubusercontent.com/92539302/139595326-d4fa5ef1-3267-4e9d-b00c-c1b75bf512d3.mp4

**Comment by ryanmcadams** [comment]
How'd you get this to run on vmware?  I cannot get it to run in a VM for the life of me.

**Comment by phGH** [comment]
vm v16.1.1 nothing special. 2c2t 6gb ram. There was no problem with vm for me.

**Comment by 4rak007** [comment]
Same problem

**Comment by frankfuu** [comment]
Might be unrelated but i find that fishing in areas where there is less green and red tends to help.

**Comment by phGH** [comment]
> Might be unrelated but i find that fishing in areas where there is less green and red tends to help.

The thing is that v1.2.1 working like a charm (except camera drifting).

**Comment by Siterizer** [comment]
Think i know what's the issue. Color wages jumped from 7: https://github.com/Siterizer/new-world-fishing-bot/blob/main/functionality/image_recognition.py
To 4:
https://github.com/Siterizer/new-world-fishing-bot/blob/2.0.0/utils/global_variables.py
Maybe will put this thing into config and make 7 default 🤔

**Comment by phGH** [comment]
> Think i know what's the issue. Color wages jumped from 7: https://github.com/Siterizer/new-world-fishing-bot/blob/main/functionality/image_recognition.py To 4: https://github.com/Siterizer/new-world-fishing-bot/blob/2.0.0/utils/global_variables.py Maybe will put this thing into config and make 7 default 🤔
> 
> Edit: Oh wait it's about 'notice' detection. May i Ask You what's the resolution your game works on?

Game runs on 1280x720.
I just replaced images in resource folder with my own from 1280x720 resolution. Worked very good on v1.2.1
With v2.0.0 I tried with stock images and replaced images (as I did with v1.2.1) and I'm getting that false positive fish detection with any images.

If it can be done like before as an option in condig it would be very cool.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
