### ISSUE TITLE
Not fixed in resulation

### ISSUE THREAD

**Issue by Jalil3** [Siterizer/new-world-fishing-bot#238]
Hi . good day . Please design a bot for different resolutions.
My resolution is 1366x768. Thankful

**Comment by ITgamers** [comment]
> Hi . good day . Please design a bot for different resolutions. My resolution is 1366x768. Thankful

Let's get the current bot smoothed out before we talk about creating additional resolution features.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
