### ISSUE TITLE
buggy,

### ISSUE THREAD

**Issue by MysticEntry-Nova64** [Siterizer/new-world-fishing-bot#239]
It sometimes reacts instantly, And sometimes it doesn't react at all.
Might react to fast? maybe?
And the box size doesn't seem to be correct the bottom of the box is ignored, I have a default location I used on the 1.2.0 version, 
Using it on the 2.0.0 version, But it seems I have to make the BOX waaaaay TALLER because the bottom part of the box doesn't work.

Got an i9 9900k, That's an 8 core and 8 threads processor. 
Might be part of the issue.

**Comment by Siterizer** [comment]
I think this may be related to resolution problem. Can You set fullHD and rerun The bot again?

**Comment by MysticEntry-Nova64** [comment]
Game is ran fullHD, windowed, 1920x1080, 
I am sorry for this but this is my last update towards this, Found one that's a bit more responsive on a different platform.
But good work 1.2.0 worked amazing and I got from 0 to 180.

**Comment by frankfuu** [comment]
Have you tried adjusting the config.yml file's log_lvl property from "INFO" to "DEBUG". I have found that it helps...a lot![see this](https://github.com/Siterizer/new-world-fishing-bot/issues/240)

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
