### ISSUE TITLE
Please add an ability to choose a display for multidisplay setups.

### ISSUE THREAD

**Issue by NoNick96** [Siterizer/new-world-fishing-bot#24]
Right now the bot only uses the monitor that's set as primary.

**Comment by raphalimam** [comment]
Had this problem, to try to get around is using an vm, so i Van put The game in The second monitor, or you can change in Windows The primary monitor and secundary.

**Comment by Siterizer** [comment]
@NoNick96 okay, can You test for me if you can set The area of green rectangle to the other monitor? (The one that is not primary)

**Comment by rogeriocamorim** [comment]
> @NoNick96 okay, can You test for me if you can set The area of a green rectangle to the other monitor? (The one that is not primary)

Not possible. My main is on the right and second on the left.
X;0 y:0 set to the corner of the main./
Even high numbers make the box disappear.

**Comment by spot88** [comment]
I can confirm this.

**Comment by NoNick96** [comment]
Tested, same situation as @rogeriocamorim .

**Comment by Mpaulo** [comment]
> Had this problem, to try to get around is using an vm, so i Van put The game in The second monitor, or you can change in Windows The primary monitor and secundary.

you got it working on Vmware? tried with workstation but it doesn recognize the hook

**Comment by NoNick96** [comment]
So setting the second display as your main pretty much solves the issue. A click or two more than a setting in the program would require, but does the job.
