### ISSUE TITLE
DEBUG Logging appears to improve catch rate

### ISSUE THREAD

**Issue by GazzaMildog** [Siterizer/new-world-fishing-bot#240]
Hi, I'm not sure on the format I should post this but from some limited testing I've noticed that enabling DEBUG logging has significantly improved the catch rate, without this enabled the bot would frequently miss the timed catch click, but after enabling it it hasn't missed once. Good work btw on the bot :)

**Comment by Siterizer** [comment]
Will look at this later. Right now i am on small vacations 🍹

**Comment by frankfuu** [comment]
Yep i've also experienced this! It improves the catch rate tremendously.

**Comment by menguepatel** [comment]
Can confirm, after updating to latest 2.0 code i noticed it wouldn't "see" the green around the catch circle..once i saw this post and went back and enabled debug it works alot more frequent..

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
