### ISSUE TITLE
(afk) issues in 2.0 / 1.2.1

### ISSUE THREAD

**Issue by qq1ng** [Siterizer/new-world-fishing-bot#241]
Something seems to have changed regarding the afk detection, just fishing doesn't prevent me from getting kicked & when using 1.2.1 and having "move around" to 0.1 eventually leads to me falling into the water and drowning.
-> someone have a way to prevent afk kicking in another way? In any of the versions that is.

2.0 (or New World being buggy) also had me multiple times throw my bobber WAY to the left of my crosshair at some point, even though the previous bobber throws of the same "session" went without issue. I do not have an explanation for that one.

Theres also the issue of 2.0 failing detection of a bite.

**Comment by 4rak007** [comment]
2.0 version getting afk detection and kicked while fishing too

**Comment by ITgamers** [comment]
Using the previous version and changed my moment to 0.0 - 0.0 haven't been kicked.

**Comment by qq1ng** [comment]
> Using the previous version and changed my moment to 0.0 - 0.0 haven't been kicked.

i think my issues with previous versions was my high repair timer. It sometimes bugs out and doesnt repair, not triggering the anti afk, so when i put my repair timer to 10 minutes i didn't move around in time lol

**Comment by syntax001** [comment]
If youre able to edit the code you could try to turn off the default anti-afk, and add this in your repairing() function, after disarming the fishing rod and before opening the inventory:

```
    releaseDelay=random.uniform(0.4, 1.2)
    press_key('a')
    sleep(releaseDelay)
    info("Moved Left For " + str(releaseDelay) + " Seconds!")
    release_key('a')
    sleep(random.randint(2,8))
    press_key('d')
    sleep(releaseDelay)
    info("Moved Right For " + str(releaseDelay) + " Seconds!")
    release_key('d')
```

If it hasnt already been imported, you need to import the 'random' library at the top like so:

`import random`

Also import 'info' in loggingwrapper if it hasnt already been:

`from wrappers.logging_wrapper import info, debug`

I suspected Amazon was looking for patterns to stop AFKers, so moving for the same amount of time every time you are executing the antiafk, is basically the same as using a macro to anti-afk, which amazon said they would try to stop. Im guessing by looking for patterns in how long you are pressing each key. By using the randomDelay in that code snippet, the character will move for a random amount of time each time it executes, so theres no pattern for Amazon to detect.
However, it will move for the same amount of time in both directions every time it executes, so youll always end up in the same spot.
Hope that helps!

**Comment by fontecic** [comment]
can confirm getting kicked for being afk using 1.2.1

**Comment by syntax001** [comment]
Try what i posted above if youre able to. Im not getting kicked with that at all.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
