### ISSUE TITLE
Login Blocked: Suspicious Software or Corrupted Install Detected

### ISSUE THREAD

**Issue by JKamsker** [Siterizer/new-world-fishing-bot#246]
Seems like its detected. Can anyone else share the experience?

![NewWorld_uSNDRRftYw](https://user-images.githubusercontent.com/11245306/140141881-38f29cf1-eccd-494c-89f2-19a588ae3950.jpg)

Its probaply not my pc, because i can login on an alt account.

**Comment by sletten93** [comment]
I just got this message with another fishing bot 'sleeping fisherman' aswell. Have anything changed for you now? Can you login?

**Comment by nezam7** [comment]
what is sleeping fisherman bot? is that a new one

**Comment by viion** [comment]
This means you've been banned. Ban waves went out for Sleeping Fisherman and this is also detected

**Comment by sletten93** [comment]
Yeah, got the permaban today. Thx for the update though

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
