### ISSUE TITLE
Few bogue

### ISSUE THREAD

**Issue by Grouik33FR** [Siterizer/new-world-fishing-bot#27]
First thank for the amazing job !

i notice two issue :

it s seems impossible to use the stop fishing button.
I have to kill the process of the bot.

Second is the bot staying in pause inifitly sometime. For exemple when fishing a chest where the tension color could be red all the time and do not go back green after some time. Is it possible to setup a « time out » for the pause meccanisme ?

thanks again
Bye

**Comment by Siterizer** [comment]
@Grouik33FR The time when bot catches that special fish where the icon od red all The time is hard to catch. Bcs bot is searching for Red/Brown/green colors.

But maybe setting pause timeout very low, like 0.4s can help with this. You can chsnge this timeout in resources/config.xml
