### ISSUE TITLE
Other screen resolutions

### ISSUE THREAD

**Issue by gssantos94** [Siterizer/new-world-fishing-bot#28]
It would be possible, who knows later, some change that allows the operation in a lower resolution, such as 1280x720.

**Comment by Siterizer** [comment]
Sure, i will put this after all other requests

**Comment by aVitomin** [comment]
Also request 1440p and >
Thanks advance

**Comment by Marow** [comment]
> @gssantos94 @aVitomin To be honest with you, right now i have bigger changes to do, so it may take a while to do so. **The only** thing that changes the resolution are 2 images located in resources/ 'fish_noticed.jpg', 'waiting_for_fish.jpg'. You can change them to your resolution and it should work.
> 
> When you do this can you pls share images you created? :)

What did you mean with changing resolutions of the images? 
fish_noticed is 30x30 and the other 32x32?

**Comment by aVitomin** [comment]
Tested 1440p - working perfectly!


![fish_noticed_1440p](https://user-images.githubusercontent.com/11780299/137220014-05e7186a-989f-4408-90f3-2ff76cca44ee.jpg)
![waiting_for_fish_1440p](https://user-images.githubusercontent.com/11780299/137220016-b93538ab-8031-442e-8c7d-58bb3d24adf8.jpg
[Downloads.zip](https://github.com/Siterizer/new-world-fishing-bot/files/7341678/Downloads.zip)
)

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
