### ISSUE TITLE
Bugs/improvements

### ISSUE THREAD

**Issue by hurrr-boop** [Siterizer/new-world-fishing-bot#30]
1.Sometimes when you catch a fish the camera will rotate 90 degrees to another angle, and you can begin fishing on land, rendering the bot useless.

2. You cannot stop fishing as the program will crash everytime. 

3. Let us save a preset on our co-ordinates for green squares.

**Comment by DaGuT** [comment]
for 3 - just set it, close the app and then reopen. It'll be saved

for 1 - I guess, you missed requirements of setting B to free camera?

**Comment by Siterizer** [comment]
I think i know why are there The crashes. The sleeps'' on the code sometimes can take too long. I will try to make global 'waiting' function. And instead of waiting 6secs IT will wait 12 times 0.5sec. and after each small wait check if The user clicked stop fishing

**Comment by hurrr-boop** [comment]
> 
> 
> for 3 - just set it, close the app and then reopen. It'll be saved
> 
> for 1 - I guess, you missed requirements of setting B to free camera?

Hey, No the Free camera is set to B :)

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
