### ISSUE TITLE
often after the animation of the fish catch the camera does not return

### ISSUE THREAD

**Issue by Sanerrr5** [Siterizer/new-world-fishing-bot#31]
often after the animation of the fish catch, the camera does not return and the character throws the fishing rod into the wall or floor

**Comment by Siterizer** [comment]
@Sanerrr5 Are You sure You set the free-look camera to 'b'?
It is important bcs in case of rare fishes the camera rotates, and the bot will try to return camera with 'b' button

**Comment by Sanerrr5** [comment]
Yes, I'm sure

**Comment by Siterizer** [comment]
Then i have no idea, add me on discord and i will try to help (i am out od pc right now, will be there on ~6h)

**Comment by Sanerrr5** [comment]
ok, on youtube and github I have met comments from people with the same problem

**Comment by Vorbild** [comment]
Could you find a fix for it? I didn't had the problem yesterday but have it now.

**Comment by yobson1** [comment]
it seems freelook sometimes get's stuck on in new world and this is when the issue arises

**Comment by Siterizer** [comment]
@yobson1 @Vorbild @Sanerrr5 one of the guys found out that, to fix that you have to click 'restore defaults' on keybinds, and assign 'b' once again. It looks like game issue. If it solved your problem close issue
