### ISSUE TITLE
Never catch fish?

### ISSUE THREAD

**Issue by turqoisehat** [Siterizer/new-world-fishing-bot#33]
I have it casting the rod but he never pulls the fish at the right time after one is on the line? it always gets away or he pulls too early??

**Comment by Culain** [comment]
can confirm. he seems to not see the "fish is biting icon"

**Comment by turqoisehat** [comment]
Trying to play with settings to get it to catch even one fish, its not happening

**Comment by turqoisehat** [comment]
NEVERMIND
Works perfect after i get out full screen

**Comment by Siterizer** [comment]
happy to hear that :DD
