### ISSUE TITLE
Suggestion for better "notice" the hook!

### ISSUE THREAD

**Issue by Slizzley** [Siterizer/new-world-fishing-bot#34]
You can add one more green-square for selecting the 'exact' coordinates of the Hook! thing. Then the bot will not search all the big green square to find fish is found notice.
Sorry for bad english

**Comment by Siterizer** [comment]
@Siterizer wow. That may be solution to run the bot on low-end pc's. Sounds very cool

**Comment by Vorbild** [comment]
I had the problem _**once**_ that the bot was just moving forward by attacking with left mouse button because there was no Fishing rod equipped. Could also fix this problem by a simple check if the hook symbol is there.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
