### ISSUE TITLE
Reeling Too Early

### ISSUE THREAD

**Issue by krinzler** [Siterizer/new-world-fishing-bot#36]
Hi, 
Thank you for the awesome script mod! 
A problem I've been facing is that from the time I cast my fishing line, my character attempts to reel in too early, before any fish is found.

**Comment by random7383** [comment]
happens the same to me. I cant get it to work

**Comment by Siterizer** [comment]
What's the bot output in ther terminal, is it
Cast fishing
Cast fishing
Cast fishing
etc?

**Comment by dsire0** [comment]
Same exact issue. On the rare occasion it does pull correctly, it does not reel in the fish unless i manually start it!

**Comment by random7383** [comment]
> What's the bot output in ther terminal, is it Cast fishing Cast fishing Cast fishing etc?

It says this in my case
https://gyazo.com/850dc81dca78e432a1e507aea2c45c6b

**Comment by dsire0** [comment]
So it works perfectly at night. During the day it reels the fish sometimes, mostly misses and often pulls too early. And when it does reel it does so sporadically

**Comment by Siterizer** [comment]
add me on discord Siterizer#8425 i will try to help you, there are a lot of thinks that could go wrong

**Comment by Siterizer** [comment]
Pls make sure, you NEED to have following settings:
Resolution 1920x1080
Window Mode **WINDOWED** that is very common issue it must be windowed even if you set 1920x1080 resolution
Brightness: 45
Contrast: 35
Video Quality: Low
Windows Scale 100%

These are the most common issues i found. Also try to remove your armor/weapons (red/green/brown colors 
could confuse the bot).
You can even try to look from abowe to only see water.

If all of the above won't help you pm me on discord

**Comment by random7383** [comment]
Using WINDOWED MODE and further tigthening the green box fixed everything.
To give more context my monitor is 1440p native and I was using 1920x1080 res fullscreen.
