### ISSUE TITLE
can not open exe file

### ISSUE THREAD

**Issue by MioPG** [Siterizer/new-world-fishing-bot#37]
when i finish setting, including game setting, rectangle and repair  position, and press "start fishing"

i can't press "stop fishing" to stop, and file is crashed,  after all i can't open exe file any more.

even i download new file, still can not open it 

is something bug like local cache need to be cleaned?

**Comment by Siterizer** [comment]
@MioPG You mean that after .exe crash you can't run this enymore? that's strange. Maybe check if your antivirus is not blocking the bot
