### ISSUE TITLE
Model Missing

### ISSUE THREAD

**Issue by imanewbe** [Siterizer/new-world-fishing-bot#4]
OSError: SavedModel file does not exist at: model/\{saved_model.pbtxt|saved_model.pb}

Can you please help me understand what I am missing? 
Can you please upload the model or put in the readme how to create the model?

Thanks

**Comment by Siterizer** [comment]
Hi. The entire repository is still under construction. (Final touches). When everything is ready I will do a big update to readme and a tutorial on how to properly install / run / etc

**Comment by imanewbe** [comment]
Sorry, it seems like I was jumping the gun.  I really like the approach and thank you for your time and work.
