### ISSUE TITLE
Pause fishing

### ISSUE THREAD

**Issue by VinnyPo0** [Siterizer/new-world-fishing-bot#40]
Hi,
I was able to use the fish bot with no problem at first, but then this problem arise when I press "start fishing", all it would do now is output "pause fishing" (I'll attach a picture). I'm using the recommended settings, Windows mode, low graphics, and binding B to freelook, not sure what the issue is.

**Comment by VinnyPo0** [comment]
![unknown](https://user-images.githubusercontent.com/73668631/135939992-84c4ff60-c1f4-42dd-83ee-d3f260a4bf82.png)

**Comment by Siterizer** [comment]
@VinnyPo0 it means, the bot spotted something red. Try to remove you clothes, don't look at the sun etc

**Comment by Logoniuss** [comment]
> @ VinnyPo0 значит, бот заметил что-то красное. Постарайтесь снять одежду, не смотрите на солнце и т. Д.

You need to come up with something new, because taking off your clothes attracts the attention of the players and they can complain.

**Comment by xenouch** [comment]
Are you sure you use good settings ? Because 80% of issues is for that. I bot 6/7h day and never have issues. My cloth are green and no problem...

WINDOWED, MAX ZOOM-IN, Free camera on B... 
And maybe for you Brightness and Contrast ?

**Comment by Siterizer** [comment]
@Logoniuss you just need to remove everythink greed/red/brown from your green rectangle. Taking off clothes is the easiest way
