### ISSUE TITLE
New World never catch issue

### ISSUE THREAD

**Issue by yobson1** [Siterizer/new-world-fishing-bot#42]
Sometimes the catch will bug at 0.0m and will never actually be caught, the tension display was orange during this and I had to manually hold LMB to purposefully break the line for fishing to be able to continue. Obviously this is a New World bug but could be mitigated within the bot, perhaps just check if we've paused on orange for X number of seconds assume it's bugged and just hold LMB until the line snaps.

**Comment by xenouch** [comment]
You use good settings ?

**Comment by yobson1** [comment]
> You use good settings ?

Did you read the issue? This is a feature request for mitigating a bug within new world, not an issue I am having with the bot.

**Comment by xenouch** [comment]
Yeah i read, and dont have this issue...

**Comment by Siterizer** [comment]
@yobson1 that's very strange bug. I never had the issue you are talking about. Can you make a prt scr next time and show me how does it looks like?

**Comment by yobson1** [comment]
Sure. To be clear it's certainly a bug with New World and not an issue with the bot. Would just be good to mitigate it within the bot so that in the event it occurs it doesn't prevent fishing from continuing. I've only seen it happen once so far so not sure how often it occurs.

**Comment by Siterizer** [comment]
@yobson1 maybe something like 
  'if the bot sees 'pause' icon for 4th in the row make 'reel' instead'
how do you think about it?

**Comment by yobson1** [comment]
That could work but it would depend on the user's setting for how long a pause is, if someone has their pause time set lower than usual it may trigger false positives.

**Comment by DaGuT** [comment]
ow, I had that problem with permamently stuck at 0 indicator. It happens pretty often.

**Comment by Siterizer** [comment]
Will leave here a note to myself:

This should work like this: 
  If pause is noticed, and the 
    (sum of the last pauses in a row) * (pause interval) > 5.0:
      reel()
  else:
    pause()

**Comment by yobson1** [comment]
> @yobson1 that's very strange bug. I never had the issue you are talking about. Can you make a prt scr next time and show me how does it looks like?

Here's what it looks like, the tension meter will stay exactly like that and the fish will never be caught.

![Screenshot](https://i.imgur.com/VPVxlbl.png)

**Comment by DaGuT** [comment]
got one in red zone :)

![image](https://user-images.githubusercontent.com/7759336/136042436-86c0f582-167f-4c59-be9f-e3eea4a36260.png)

**Comment by liao-frank** [comment]
> Should be gucci now: [731b971](https://github.com/Siterizer/new-world-fishing-bot/commit/731b97128c8ea728d7b598dea45dcb51b3f1eb92)

This issue happens to me sometimes too. It's not necessarily orange or red; it could be green too. It's just that the reeling gets stuck at the very end and you can't reel any further. The fish never goes away either.

I fix it manually by opening and closing my inventory, which clears the stuck minigame and lets me cast again.

If you ever get around to making the bot more stateful, might be worth adding a check to see if the reeling minigame has been going on for too long (> 30 seconds) and to open/close the inventory.

**Comment by liao-frank** [comment]
Seems like maybe the behavior changed. I now have to right-click to get out of this.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
