### ISSUE TITLE
shutdown due to inactivity

### ISSUE THREAD

**Issue by artemsiberiangit** [Siterizer/new-world-fishing-bot#45]
There is a shutdown due to inactivity, it is required that the character moves from the point every 5 minutes.

**Comment by tallglen** [comment]
I was playing last night and when my pole broke, the clicks from the bot attempting to cast enabled me to stay logged in for 6+ hours until the next morning.  I don't think movement is required unless your server got some new AFK detection logic added.

**Comment by Siterizer** [comment]
probable the bot crashed i heard that it can happen. Working on this
