### ISSUE TITLE
Suggestion for repair position

### ISSUE THREAD

**Issue by SeattleBLACK** [Siterizer/new-world-fishing-bot#47]
Comes from a bot I've been working on myself, pretty new to programming in general so I suppose this is meant to just be a concept. I've used yours in the mean time until I get mine working, so hope I could help contribute in some way.

Basically I found the sliders for the repair position a little tedious, so I thought a hotkey to set it would be nice. The idea is to have the user move their mouse to the rod slot in their inventory then hit INSERT to set its position.

```
class Repair:
    x = 0
    y = 0

    def set_position(): 
        mouseX, mouseY = mouse.get_position()
        print(f"[INFO] New Repair Position:   {mouseX} and {mouseY}")
        Repair.x = mouseX
        Repair.y = mouseY

    def get_position():
        return Repair.x, Repair.y

. . .

keyboard.add_hotkey('insert',callback=(Repair.set_position))
```
(Then call get_position somewhere in one of your loops when you need to)

It seems you like personalization so of course you could make the hotkey configurable.
Thanks for reading.

**Comment by Siterizer** [comment]
Hey, that's a pretty cool idea, thank you will think about that in next releases

**Comment by Siterizer** [comment]
will try in the next week release

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
