### ISSUE TITLE
Rod getting repaired way too often?

### ISSUE THREAD

**Issue by 01d5ch001** [Siterizer/new-world-fishing-bot#53]
I've set the green box for the rod repairing in the top left corner of the rod icon (as on the screenshot).
I don't know if it's intended or not but the script repairs the rod when it's durability is above 90% which means it uses a lot of repair parts when not needed.

Am I setting it up wrong or it's intended to repair that often?

**Comment by Logoniuss** [comment]
There is also a setting in seconds, the default is 400, change it as much as you need.

**Comment by 01d5ch001** [comment]
@Logoniuss oh wow, I didn't even noticed it... Thanks, now it makes more sense :D
