### ISSUE TITLE
Running in VMware Workstation

### ISSUE THREAD

**Issue by jordan351** [Siterizer/new-world-fishing-bot#54]
Hi there, 
I'm trying to make it work through a VM, cause I need to use my PC during botting and not just looking at it ^^

It always pulls too early while no fish bites. 

Without using any VM, it works, but not inside :'(

**Comment by Siterizer** [comment]
i don't know much about using VM. 
But as far as i know there could be a problem with setting the proper resolution
Could you pls tell me what's the terminal output?

**Comment by hotpoopy** [comment]
> > i don't know much about using VM. But as far as i know there could be a problem with setting the proper resolution Could you pls tell me what's the terminal output?
> 
> its a resolution problem, i tried many ways on Vmware and manage to make it work, but the Vm should be in fullscreen mode (i just minimize it after that)

how did you manage to run new world on VMWARE? i tried but it gave me an error about meeting minimum requirement

**Comment by Siterizer** [comment]
then i gonna close the issue
