### ISSUE TITLE
Log Level Behaviour '0'

### ISSUE THREAD

**Issue by seedlord** [Siterizer/new-world-fishing-bot#55]
If there is no recognized result_from_model it will spam the console with "Waiting for fish...". 
It would be nice to have this message only appear 1x until the next fish.
Corresponding code from functionality/fishing_loop.py:
```
...
    if result_from_model == '0': # 0 - model does not match any data (not fish captured yet)
        info("Waiting for fish...")
        return '0'
...
```
Im not that familiar with python but i thought something like this:
```
onetimehelper = 0
...
    if result_from_model == '0': # 0 - model does not match any data (not fish captured yet)
        if onetimehelper == 0:
            info("Waiting for fish...")
            onetimehelper = 1
        return '0'
...
```
and in one of the other cases 1-4 onetimehelper should be set to 0 again.

**Comment by Siterizer** [comment]
Closing https://github.com/Siterizer/new-world-fishing-bot/commit/dcf9e7607bf8362447916c60398a30dda9422080
