### ISSUE TITLE
[INFO] Pause fishing

### ISSUE THREAD

**Issue by Wahiys** [Siterizer/new-world-fishing-bot#60]
now bot do nothing except pause

[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing
[INFO] Pause fishing

**Comment by Trigun87** [comment]
if u have red hairs or something red it will not works, cover with helmet or armor :-D
