### ISSUE TITLE
[Question] Sound macro

### ISSUE THREAD

**Issue by Slizzley** [Siterizer/new-world-fishing-bot#63]
Your bot working with pixels. Is there a way to make a bot working with sounds?. As you know the fishing "Hook!" "Reel" sounds can be used to automatic fish.

**Comment by Siterizer** [comment]
Wait that's actually rly good idea. I could even train a model via neutral network with all the sounds. Thanks for the advice!

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
