### ISSUE TITLE
Repair Kit Support

### ISSUE THREAD

**Issue by tallglen** [Siterizer/new-world-fishing-bot#69]
May we please have an option to be able to use Repair Kits to repair?

When you have repair kits in your inventory, the key combination on click to repair the pole is T+click, then the same E to confirm.  I run out of repair parts frequently so I now buy repair kits.

**Comment by Siterizer** [comment]
@tallglen that's why you should use wooden fishing rod :) i know there is lower chance to get rare fish, but it costs 0 gold and 0 repair parts to repair
