### ISSUE TITLE
Cant make this to work :(

### ISSUE THREAD

**Issue by Oplateks** [Siterizer/new-world-fishing-bot#70]
So most of the process works great! (Thank you!)
Could anyone give me any advice, how to fix this pls?

Everything works fine until the reeling. The bot starts reeling and releasing, but about halfway through it just stops completely. At this moment it just wants to start over. :(

Thank you!

Edit: or , it waits for fish, and it finds one, activate the reeling, but instead of reeling, it wants to "Cast fishing rod".
When I try to stop the bot, it goes unresponsive and wont stop. Windows 10

Example: https://imgur.com/FKpq19U
Starts reeling etc just fine, then it takes a pause and starts over while it did not finish.

Another screenshot:
https://imgur.com/G8zgX7z

The bot is waiting for fish and "confirms it" but completely skips the reeling process and wants to start over.

**Comment by Siterizer** [comment]
Check your brightnes etc. It clearly can't recognize 'green' color
