### ISSUE TITLE
Auto assign sizes and positions of rectangles by default on differents resolutions

### ISSUE THREAD

**Issue by benjaminaudet** [Siterizer/new-world-fishing-bot#75]
- it should manage at least the 1920x1080 resolution
- also 2K and 4K

PS: there should be ways to control the application through hotkeys, like for example the action of the button "Start/Stop fishing".

**Comment by Siterizer** [comment]
will do that in the next weekend

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
