### ISSUE TITLE
Not reeling in fish

### ISSUE THREAD

**Issue by CJWI86** [Siterizer/new-world-fishing-bot#76]
Casting the rod, and then when it catches it's just letting it time out. I have all my settings set at 1080p low, box is in the right spot, contrast/brightness all set correctly., windows scaling is at 100% Any idea what's causing this? 

[INFO] Cast fishing rod
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Found a fish!
[INFO] Cast fishing rod
[INFO] Cast fishing rod

**Comment by Siterizer** [comment]
i think the problem is brightness/contrast it clearly can't see 'green' color

**Comment by mikegervo** [comment]
Hi, I am experiencing the same thing.
My log looks like this:
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Waiting for fish...
[INFO] Found a fish!
[INFO] Cast fishing rod
[INFO] Cast fishing rod

I tried +/- 20 in brightness didnt help.

**Comment by Siterizer** [comment]
add me on discord:
Siterizer#8425
