### ISSUE TITLE
Found a fish but not reeling in.

### ISSUE THREAD

**Issue by VivienFreb** [Siterizer/new-world-fishing-bot#82]
Hello,

I wanted to give a try about this to see how it would work but I can't manage to get it to work.
Whever I find a fish, the mouse is pressed for a certain amount of time but then a new loop start and the bot is not trying to catch the fish.

I tried moving to another place, maybe it was colors problems like orange or something like that, changed the square size but nothing changed.

I've done every steps in the installation tutorial about brightness, contrast...

I'm attaching a screenshot of the debug file.

Thanks!

![bug](https://user-images.githubusercontent.com/33395168/136656603-fceccfe5-8816-4433-b029-0eff6cc52877.jpg)

**Comment by Siterizer** [comment]
If you are sure abut brightness etc add me on discord: Siterizer#8425

**Comment by DerekLeeHH** [comment]
> Using the latest version and my own screen colors (green, orange and red state), it works perfectly. Maybe you don't even need to change any other visual settings as long as you chose your own colors.

How do you determine your own screen color?
