### ISSUE TITLE
Windows: .exe not response after 1 min, loop bug 

### ISSUE THREAD

**Issue by Kafigueiredo** [Siterizer/new-world-fishing-bot#9]
Hi !
 
After running the .exe, after 2 minutes the app crashes. I think that the loop resets itself without ever going to the end. My logs:
```
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 0.67 s
[DEBUG] Pause for: 5 s
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 0.8 s
[DEBUG] Pause for: 5 s
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 0.8 s
[DEBUG] Pause for: 5 s
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 0.93 s
[DEBUG] Pause for: 5 s
[DEBUG] starting new loop
[INFO] Cast fishing rod
[DEBUG] Pause for: 1.0 s
```

I'm on windows 11.

Any idea ?

(ps: Thank you for the work already done)

**Comment by Siterizer** [comment]
Hi, thank you very much! it's all my fault i made a typo in this file:
https://github.com/Siterizer/new-world-fishing-bot/blob/main/functionality/fishing_actions.py
you see that 'r' ad the end of the file? xd. Give me a couple of hours and i will make new release

**Comment by Siterizer** [comment]
Ok, typo corrected, everything should work. Additionally, when catching a unique fish, the bot will return to the default position of a camera.
https://github.com/Siterizer/new-world-fishing-bot/commit/cfec403a1c82b65807536a01f43b50bc00effa85
  An update for the release was made:
https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v1.1.0.
  If you think everything works then close the issue

**Comment by Siterizer** [comment]
Remember to change your game settings :)
https://github.com/Siterizer/new-world-fishing-bot

**Comment by Trobyss** [comment]
@Siterizer Hi ! 
```An update for the release was made:
https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v1.1.0.
If you think everything works then close the issue```

Are u sure ? It still the old tag no ?

**Comment by Siterizer** [comment]
@Trobyss 

  Yes of course you are right. Sorry for the mistake, but this is my first 'big' project. Thanks so much for noticing this
  https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v1.1.1 (yt viedo inc :DDD )

**Comment by Trobyss** [comment]
@Siterizer 

Ahah don't worry ! Seem's like good know... but I have an issue with camera. I set "B" for camera but after the first fish, my character look at the floor and can't re-use fishing ... any idea ?

**Comment by Siterizer** [comment]
@Trobyss 
  Add me on discord Siterizer#8425

**Comment by Trobyss** [comment]
U can close the issue ;) thanks for the reactivity !
