### ISSUE TITLE
Can't get it to start

### ISSUE THREAD

**Issue by DogeBR** [Siterizer/new-world-fishing-bot#91]
Forgive me but I need some help.
I can't get it to start at all, followed all steps, set up the area above the character, looking straight at water and naked to prefent any reds, nothing happens. If i go to youtube with the bot running the clicks happen (ocassionally pausing/unpausing vids), but in game it doesnt even throw the rod. I tried leaving the bot on screen and just moving mouse into the game window and also tried clicking in the game window, nothing works. I'm prolly doing something wrong, or I've missed something, but i have no idea what. Help?

**Comment by bulderdash** [comment]
Run administrtor exe
