### ISSUE TITLE
where is exe?

### ISSUE THREAD

**Issue by DeityofGreed** [Siterizer/new-world-fishing-bot#92]
I'm not sure how to run python stuff. When i click bot.py a window pops up for just second before vanishing.

**Comment by raphalimam** [comment]
If you download the https://github.com/Siterizer/new-world-fishing-bot/releases you should get the exe and just need to run, but if you want to run in your on python you need to download python and install the libraries to be able tu run the bot.py correctly, there is an small tutorial in the readme about how to run in python, but you can just download the release with the exe
