### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by vanillainanutshell** [Siterizer/new-world-fishing-bot#99]
cant download the requirements

**Comment by zak062** [comment]
I ran into this issue along with a few others while trying to install. I finally got it to work with these steps (idk which one actually "fixed" it) I had tried all the below steps at other times but this order of steps are what worked for me 

Uninstalled Python
Downgrade to 3.8.10 (https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip)
Installed each package listed in requirements.txt with pip
Download zip of bot, extract to directory
created the virtual env
activated scripts
ran pip -install installpath\requirements.txt
cd installdirectory
py bot.py

**Comment by Acanis87** [comment]
I installed the 3.8.10 and I was able to install the requirements now.

But...:

> C:\Program Files\Python38\python.exe: can't open file 'bot.py': [Errno 2] No such file or directory

I didnt download the ZIP of the bot ^^

Your "cd instalation_directory" was the thing, that I did need... Now its starting! Dont know, if it will work - but it did start! yay :D

**Comment by Acanis87** [comment]
Hm, now its "running" and casting the rod... The log even says, that it found a fish, but its not reeling it... Never... Changed all graphic settings and so on... Huh... Sad :( 

And the UI is freezing, if I want to show the searching area again... The UI seems to be overwhelmed, even with my cpu still having good power left...
